/*******************************************************************
 
Copyright (c) 2012 by Silicon Motion, Inc. (SMI)

Permission is hereby granted, free of charge, to any person obtaining a copy 
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to 
do so, subject to the following conditions:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
NONINFRINGEMENT.  IN NO EVENT SHALL MILL CHEN, MONK LIU, ALEX YAO, 
SUNNY YANG, ILENA ZHOU, MANDY WANG OR COPYRIGHT 
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
OTHER DEALINGS IN THE SOFTWARE.
 
*******************************************************************/

#define GPIO_DATA_LOW                                   0x010000

#define GPIO_DATA_HIGH                                  0x010004
#define GPIO_DATA_HIGH_47                               15:15
#define GPIO_DATA_HIGH_46                               14:14

#define GPIO_DATA_DIR_HIGH                              0x01000C
#define GPIO_DATA_DIR_HIGH_47                           15:15
#define GPIO_DATA_DIR_HIGH_47_INPUT                     0
#define GPIO_DATA_DIR_HIGH_47_OUTPUT                    1
#define GPIO_DATA_DIR_HIGH_46                           14:14
#define GPIO_DATA_DIR_HIGH_46_INPUT                     0
#define GPIO_DATA_DIR_HIGH_46_OUTPUT                    1

#define GPIO_DATA_DIRECTION_LOW                         0x010008
#define GPIO_DATA_DIRECTION_LOW_31                      31:31
#define GPIO_DATA_DIRECTION_LOW_31_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_31_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_30                      30:30
#define GPIO_DATA_DIRECTION_LOW_30_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_30_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_29                      29:29
#define GPIO_DATA_DIRECTION_LOW_29_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_29_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_28                      28:28
#define GPIO_DATA_DIRECTION_LOW_28_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_28_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_27                      27:27
#define GPIO_DATA_DIRECTION_LOW_27_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_27_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_26                      26:26
#define GPIO_DATA_DIRECTION_LOW_26_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_26_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_25                      25:25
#define GPIO_DATA_DIRECTION_LOW_25_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_25_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_24                      24:24
#define GPIO_DATA_DIRECTION_LOW_24_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_24_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_23                      23:23
#define GPIO_DATA_DIRECTION_LOW_23_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_23_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_22                      22:22
#define GPIO_DATA_DIRECTION_LOW_22_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_22_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_21                      21:21
#define GPIO_DATA_DIRECTION_LOW_21_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_21_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_20                      20:20
#define GPIO_DATA_DIRECTION_LOW_20_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_20_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_19                      19:19
#define GPIO_DATA_DIRECTION_LOW_19_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_19_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_18                      18:18
#define GPIO_DATA_DIRECTION_LOW_18_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_18_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_17                      17:17
#define GPIO_DATA_DIRECTION_LOW_17_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_17_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_16                      16:16
#define GPIO_DATA_DIRECTION_LOW_16_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_16_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_15                      15:15
#define GPIO_DATA_DIRECTION_LOW_15_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_15_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_14                      14:14
#define GPIO_DATA_DIRECTION_LOW_14_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_14_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_13                      13:13
#define GPIO_DATA_DIRECTION_LOW_13_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_13_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_12                      12:12
#define GPIO_DATA_DIRECTION_LOW_12_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_12_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_11                      11:11
#define GPIO_DATA_DIRECTION_LOW_11_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_11_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_10                      10:10
#define GPIO_DATA_DIRECTION_LOW_10_INPUT                0
#define GPIO_DATA_DIRECTION_LOW_10_OUTPUT               1
#define GPIO_DATA_DIRECTION_LOW_9                       9:9
#define GPIO_DATA_DIRECTION_LOW_9_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_9_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_8                       8:8
#define GPIO_DATA_DIRECTION_LOW_8_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_8_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_7                       7:7
#define GPIO_DATA_DIRECTION_LOW_7_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_7_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_6                       6:6
#define GPIO_DATA_DIRECTION_LOW_6_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_6_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_5                       5:5
#define GPIO_DATA_DIRECTION_LOW_5_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_5_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_4                       4:4
#define GPIO_DATA_DIRECTION_LOW_4_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_4_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_3                       3:3
#define GPIO_DATA_DIRECTION_LOW_3_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_3_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_2                       2:2
#define GPIO_DATA_DIRECTION_LOW_2_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_2_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_1                       131
#define GPIO_DATA_DIRECTION_LOW_1_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_1_OUTPUT                1
#define GPIO_DATA_DIRECTION_LOW_0                       0:0
#define GPIO_DATA_DIRECTION_LOW_0_INPUT                 0
#define GPIO_DATA_DIRECTION_LOW_0_OUTPUT                1

#define GPIO_DATA_DIRECTION_HIGH                        0x01000C
#define GPIO_DATA_DIRECTION_HIGH_63                     31:31
#define GPIO_DATA_DIRECTION_HIGH_63_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_63_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_62                     30:30
#define GPIO_DATA_DIRECTION_HIGH_62_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_62_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_61                     29:29
#define GPIO_DATA_DIRECTION_HIGH_61_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_61_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_60                     28:28
#define GPIO_DATA_DIRECTION_HIGH_60_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_60_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_59                     27:27
#define GPIO_DATA_DIRECTION_HIGH_59_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_59_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_58                     26:26
#define GPIO_DATA_DIRECTION_HIGH_58_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_58_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_57                     25:25
#define GPIO_DATA_DIRECTION_HIGH_57_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_57_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_56                     24:24
#define GPIO_DATA_DIRECTION_HIGH_56_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_56_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_55                     23:23
#define GPIO_DATA_DIRECTION_HIGH_55_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_55_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_54                     22:22
#define GPIO_DATA_DIRECTION_HIGH_54_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_54_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_53                     21:21
#define GPIO_DATA_DIRECTION_HIGH_53_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_53_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_52                     20:20
#define GPIO_DATA_DIRECTION_HIGH_52_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_52_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_51                     19:19
#define GPIO_DATA_DIRECTION_HIGH_51_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_51_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_50                     18:18
#define GPIO_DATA_DIRECTION_HIGH_50_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_50_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_49                     17:17
#define GPIO_DATA_DIRECTION_HIGH_49_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_49_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_48                     16:16
#define GPIO_DATA_DIRECTION_HIGH_48_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_48_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_47                     15:15
#define GPIO_DATA_DIRECTION_HIGH_47_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_47_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_46                     14:14
#define GPIO_DATA_DIRECTION_HIGH_46_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_46_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_45                     13:13
#define GPIO_DATA_DIRECTION_HIGH_45_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_45_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_44                     12:12
#define GPIO_DATA_DIRECTION_HIGH_44_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_44_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_43                     11:11
#define GPIO_DATA_DIRECTION_HIGH_43_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_43_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_42                     10:10
#define GPIO_DATA_DIRECTION_HIGH_42_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_42_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_41                     9:9
#define GPIO_DATA_DIRECTION_HIGH_41_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_41_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_40                     8:8
#define GPIO_DATA_DIRECTION_HIGH_40_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_40_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_39                     7:7
#define GPIO_DATA_DIRECTION_HIGH_39_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_39_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_38                     6:6
#define GPIO_DATA_DIRECTION_HIGH_38_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_38_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_37                     5:5
#define GPIO_DATA_DIRECTION_HIGH_37_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_37_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_36                     4:4
#define GPIO_DATA_DIRECTION_HIGH_36_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_36_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_35                     3:3
#define GPIO_DATA_DIRECTION_HIGH_35_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_35_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_34                     2:2
#define GPIO_DATA_DIRECTION_HIGH_34_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_34_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_33                     1:1
#define GPIO_DATA_DIRECTION_HIGH_33_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_33_OUTPUT              1
#define GPIO_DATA_DIRECTION_HIGH_32                     0:0
#define GPIO_DATA_DIRECTION_HIGH_32_INPUT               0
#define GPIO_DATA_DIRECTION_HIGH_32_OUTPUT              1

#define GPIO_INTERRUPT_SETUP                            0x010010
#define GPIO_INTERRUPT_SETUP_TRIGGER_54                 22:22
#define GPIO_INTERRUPT_SETUP_TRIGGER_54_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_54_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_53                 21:21
#define GPIO_INTERRUPT_SETUP_TRIGGER_53_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_53_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_52                 20:20
#define GPIO_INTERRUPT_SETUP_TRIGGER_52_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_52_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_51                 19:19
#define GPIO_INTERRUPT_SETUP_TRIGGER_51_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_51_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_50                 18:18
#define GPIO_INTERRUPT_SETUP_TRIGGER_50_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_50_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_49                 17:17
#define GPIO_INTERRUPT_SETUP_TRIGGER_49_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_49_LEVEL           1
#define GPIO_INTERRUPT_SETUP_TRIGGER_48                 16:16
#define GPIO_INTERRUPT_SETUP_TRIGGER_48_EDGE            0
#define GPIO_INTERRUPT_SETUP_TRIGGER_48_LEVEL           1
#define GPIO_INTERRUPT_SETUP_ACTIVE_54                  14:14
#define GPIO_INTERRUPT_SETUP_ACTIVE_54_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_54_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_53                  13:13
#define GPIO_INTERRUPT_SETUP_ACTIVE_53_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_53_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_52                  12:12
#define GPIO_INTERRUPT_SETUP_ACTIVE_52_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_52_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_51                  11:11
#define GPIO_INTERRUPT_SETUP_ACTIVE_51_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_51_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_50                  10:10
#define GPIO_INTERRUPT_SETUP_ACTIVE_50_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_50_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_49                  9:9
#define GPIO_INTERRUPT_SETUP_ACTIVE_49_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_49_HIGH             1
#define GPIO_INTERRUPT_SETUP_ACTIVE_48                  8:8
#define GPIO_INTERRUPT_SETUP_ACTIVE_48_LOW              0
#define GPIO_INTERRUPT_SETUP_ACTIVE_48_HIGH             1
#define GPIO_INTERRUPT_SETUP_ENABLE_54                  6:6
#define GPIO_INTERRUPT_SETUP_ENABLE_54_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_54_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_53                  5:5
#define GPIO_INTERRUPT_SETUP_ENABLE_53_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_53_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_52                  4:4
#define GPIO_INTERRUPT_SETUP_ENABLE_52_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_52_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_51                  3:3
#define GPIO_INTERRUPT_SETUP_ENABLE_51_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_51_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_50                  2:2
#define GPIO_INTERRUPT_SETUP_ENABLE_50_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_50_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_49                  1:1
#define GPIO_INTERRUPT_SETUP_ENABLE_49_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_49_INTERRUPT        1
#define GPIO_INTERRUPT_SETUP_ENABLE_48                  0:0
#define GPIO_INTERRUPT_SETUP_ENABLE_48_GPIO             0
#define GPIO_INTERRUPT_SETUP_ENABLE_48_INTERRUPT        1

#define GPIO_INTERRUPT_STATUS                           0x010014
#define GPIO_INTERRUPT_STATUS_54                        22:22
#define GPIO_INTERRUPT_STATUS_54_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_54_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_54_RESET                  1
#define GPIO_INTERRUPT_STATUS_53                        21:21
#define GPIO_INTERRUPT_STATUS_53_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_53_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_53_RESET                  1
#define GPIO_INTERRUPT_STATUS_52                        20:20
#define GPIO_INTERRUPT_STATUS_52_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_52_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_52_RESET                  1
#define GPIO_INTERRUPT_STATUS_51                        19:19
#define GPIO_INTERRUPT_STATUS_51_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_51_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_51_RESET                  1
#define GPIO_INTERRUPT_STATUS_50                        18:18
#define GPIO_INTERRUPT_STATUS_50_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_50_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_50_RESET                  1
#define GPIO_INTERRUPT_STATUS_49                        17:17
#define GPIO_INTERRUPT_STATUS_49_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_49_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_49_RESET                  1
#define GPIO_INTERRUPT_STATUS_48                        16:16
#define GPIO_INTERRUPT_STATUS_48_INACTIVE               0
#define GPIO_INTERRUPT_STATUS_48_ACTIVE                 1
#define GPIO_INTERRUPT_STATUS_48_RESET                  1


